config/routes.rb
NinetynineCats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new] do
    patch "/approve", to: "cat_rental_requests#approve"
    patch "/deny", to: "cat_rental_requests#deny"
  end

  resources :users, only: [:create, :new]
  resource :session
end

app/models/cat.rb
class Cat < ActiveRecord::Base

  validates :age, :numericality => true
  validates :color, inclusion: { in: ['black', 'blue', 'brown', 'tan', 'orange']}
  validates :sex, inclusion: { in: ['m', 'f']}
  validates :age, :color, :sex, :name, :birthdate, :presence => true

  has_many :cat_rental_requests, :dependent => :destroy



end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base

  validates :status, inclusion: { in: ['PENDING', "APPROVED", "DENIED"] }
  validates :status, :cat_id, :end_date, :start_date, :presence => true
  validate :overlapping_approved_requests

  belongs_to :cat


  def approve!
    ActiveRecord::Base.transaction do
      self.status = "APPROVED"
      self.save
      @cat = Cat.find(self.cat_id)
      pending = @cat.cat_rental_requests.where(status: 'PENDING')
      pending.each do |pending_request|
        if overlapping_requests(pending_request)
          pending_request.deny!
        end
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save
  end


  private

  def overlapping_requests(cat_request)
    (cat_request.start_date..cat_request.end_date)
    .include?(self.start_date) ||
    (cat_request.start_date..cat_request.end_date)
    .include?(self.end_date) ||
    (self.start_date..self.end_date)
    .include?(cat_request.end_date)
  end

  def overlapping_approved_requests
    return if self.cat_id.nil? || self.status == "DENIED"
    @cat = Cat.find(self.cat_id)
    approved = @cat.cat_rental_requests.where(status: 'APPROVED')

    approved.each do |request|
      if overlapping_requests(request)
        errors[:cat_rental_request] << "cannot overlap rental dates"
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :reset_session_token

  def self.find_by_credentials(user_name, pw)
    u = User.find_by_user_name(user_name)
    if u.is_password?(pw)
      u
    else
      nil
    end
  end

  def password=(pw)
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def reset_session_token
    self.session_token ||= reset_session_token!
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  include SessionsHelper
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cats = Cat.all
    @cat_request = CatRentalRequest.new
  end

  def create
    @cats = Cat.all

    @cat_request = CatRentalRequest.new(rental_params)
    if @cat_request.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def approve
    @cat_request = CatRentalRequest.find(params[:cat_rental_request_id])
    @cat_request.approve!
    redirect_to :back
  end

  def deny
    @cat_request = CatRentalRequest.find(params[:cat_rental_request_id])
    @cat_request.deny!
    redirect_to :back
  end

  private

  def rental_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birthdate, :age)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
          params[:user][:username],
          params[:user][:password]
    )

    if user.nil?
      render :new
    else
      user.reset_session_token!
      self.current_user = user
      redirect_to cats_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_session_url
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="post" accept-charset="utf-8">
	<% @cat_request.errors.full_messages.each do |msg| %>
	      <p><%= msg %></p>
	  <% end %>


	<select name= "cat_rental_request[cat_id]" >
		<option type="hidden"></option>
		<% @cats.each do |cat| %>
		<option value= "<%= cat.id%>"><%= cat.name %></option>
		<%end%>
	<select>

	<label for="cat_start_date">Start date</label>
	<input name="cat_rental_request[start_date]" id="cat_start_date" type="date" 		value="<%= @cat_request.start_date %>"/>
	<label for="cat_end_date">End date</label>
	<input name="cat_rental_request[end_date]" id="cat_end_date" type="date" 		value="<%= @cat_request.end_date %>"/>

		<input type="submit" />
</form>

app/views/cats/_form.html.erb
<form action="<%= if @cat.persisted?
										cat_url(@cat)
									else
										cats_url
									end %>" method="post" accept-charset="utf-8">

	<%'<input type = "hidden" name="_method" value = "patch">' if @cat.persisted? %>

	<label for="name">Name</label>
	<input type="text" name="cat[name]" id="name" value= "<%= @cat.name %>" />

	<label for="age">Age</label>
	<input type="text" name="cat[age]" id="age" value= "<%= @cat.age %>"/>

	<label for="male">Male</label>
	<input type="radio" name="cat[sex]" value="m" id="male"
	<%= "checked" if @cat.sex == "m" %> />
	<label for= "female">Female</label>
	<input type="radio" name="cat[sex]" value="f" id="female"
	<%= "checked" if @cat.sex == "f" %>/>

	<select name= "cat[color]" >
		<option type="hidden"></option>
		<% colors = ['black', 'blue', 'brown', 'tan', 'orange']%>
		<% colors.each do |color|%>
		<option <%= "selected" if @cat.color == color %>><%= color %></option>
		<%end%>
	<select>

	<label for="cat_birth_date">Birth date</label>
	<input name="cat[birthdate]" id="cat_birth_date" type="date"
	value="<%= @cat.birthdate %>"></input>


	<p><input type="submit"></p>


</form>

app/views/cats/edit.html.erb
<%= render :partial => 'form' %>

app/views/cats/index.html.erb
<ul>
	<% @cats.each do |cat| %>
		<li><%= link_to cat.name, cat_url(cat) %></li>
	<% end %>
</ul>


<p>
	<%= link_to "Request Cat", new_cat_rental_request_url, :method => :get%>

</p>

app/views/cats/new.html.erb
	<%= render :partial => 'form' %>

app/views/cats/show.html.erb
<table>
	<tr>
		<th>Name</th>
		<th>Age</th>
		<th>Sex</th>
		<th>Color</th>
		<th>Birthdate</th>
	</tr>
	<tr>
		<td><%= @cat.name %></td>
		<td><%= @cat.age %></td>
		<td><%= @cat.sex %></td>
		<td><%= @cat.color %></td>
		<td><%= @cat.birthdate%></td>
	</tr>
</table>

<ul>
<% @cat.cat_rental_requests.order(:start_date).each do |rental| %>
	<li>
		<%= "#{rental.start_date} to #{rental.end_date}:  #{rental.status}"%>
		<% if rental.status == 'PENDING'%>
		<%= button_to "approve", cat_rental_request_approve_url(rental), method: :patch%>
		<%= button_to "deny", cat_rental_request_deny_url(rental), method: :patch%>
		<%end %>
	</li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetynineCats</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:errors] %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post" accept-charset="utf-8">

	<label for="username">User Name!</label>
	<input type="text" name="user[user_name]" id="username"/>

	<label for="Password">Password</label>
	<input type="password" name="user[password]" id="password"/>

	<p><input type="submit"></p>
</form>